/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctOption' : IDL.Text,
  'image' : ExternalBlob,
});
export const Answer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedOption' : IDL.Text,
});
export const Time = IDL.Int;
export const TestResult = IDL.Record({
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(Answer),
  'submittedAt' : Time,
  'score' : IDL.Nat,
  'testId' : IDL.Nat,
});
export const CompleteTest = IDL.Record({
  'id' : IDL.Nat,
  'isPublished' : IDL.Bool,
  'name' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'questions' : IDL.Vec(Question),
});
export const Class = IDL.Variant({
  'dropper' : IDL.Null,
  'eleventh' : IDL.Null,
  'twelfth' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'fullName' : IDL.Text,
  'hasVisitedAdmin' : IDL.Bool,
  'contactNumber' : IDL.Nat,
  'userClass' : Class,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getAllTests' : IDL.Func([], [IDL.Vec(CompleteTest)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getPublishedTests' : IDL.Func([], [IDL.Vec(CompleteTest)], ['query']),
  'getTestById' : IDL.Func([IDL.Nat], [CompleteTest], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdminBeenVisited' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAdminVisited' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTestResult' : IDL.Func([IDL.Nat, IDL.Vec(Answer), IDL.Nat], [], []),
  'togglePublishTest' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
  'updateQuestion' : IDL.Func([IDL.Nat, ExternalBlob, IDL.Text], [], []),
  'updateTest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctOption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Answer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedOption' : IDL.Text,
  });
  const Time = IDL.Int;
  const TestResult = IDL.Record({
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(Answer),
    'submittedAt' : Time,
    'score' : IDL.Nat,
    'testId' : IDL.Nat,
  });
  const CompleteTest = IDL.Record({
    'id' : IDL.Nat,
    'isPublished' : IDL.Bool,
    'name' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'questions' : IDL.Vec(Question),
  });
  const Class = IDL.Variant({
    'dropper' : IDL.Null,
    'eleventh' : IDL.Null,
    'twelfth' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'fullName' : IDL.Text,
    'hasVisitedAdmin' : IDL.Bool,
    'contactNumber' : IDL.Nat,
    'userClass' : Class,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getAllTests' : IDL.Func([], [IDL.Vec(CompleteTest)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getPublishedTests' : IDL.Func([], [IDL.Vec(CompleteTest)], ['query']),
    'getTestById' : IDL.Func([IDL.Nat], [CompleteTest], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdminBeenVisited' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAdminVisited' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTestResult' : IDL.Func([IDL.Nat, IDL.Vec(Answer), IDL.Nat], [], []),
    'togglePublishTest' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
    'updateQuestion' : IDL.Func([IDL.Nat, ExternalBlob, IDL.Text], [], []),
    'updateTest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };