/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionId' : bigint, 'selectedOption' : string }
export type Class = { 'dropper' : null } |
  { 'eleventh' : null } |
  { 'twelfth' : null };
export interface CompleteTest {
  'id' : bigint,
  'isPublished' : boolean,
  'name' : string,
  'durationMinutes' : bigint,
  'questions' : Array<Question>,
}
export type ExternalBlob = Uint8Array;
export interface Question {
  'id' : bigint,
  'correctOption' : string,
  'image' : ExternalBlob,
}
export interface TestResult {
  'userId' : Principal,
  'answers' : Array<Answer>,
  'submittedAt' : Time,
  'score' : bigint,
  'testId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'fullName' : string,
  'hasVisitedAdmin' : boolean,
  'contactNumber' : bigint,
  'userClass' : Class,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a new question. Admin only.
   */
  'addQuestion' : ActorMethod<[ExternalBlob, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new test. Admin only.
   */
  'createTest' : ActorMethod<[string, bigint, Array<bigint>], bigint>,
  /**
   * / Delete a question. Admin only.
   */
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  /**
   * / Get all questions. Admin only.
   */
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  /**
   * / Get all test results. Admin only.
   */
  'getAllResults' : ActorMethod<[], Array<TestResult>>,
  /**
   * / Get all tests (published and unpublished). Admin only.
   */
  'getAllTests' : ActorMethod<[], Array<CompleteTest>>,
  /**
   * / Get all registered users. Admin only.
   */
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  /**
   * / Get the calling user's own profile. Requires #user role.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get the calling user's profile. Requires #user role.
   */
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  /**
   * / Get the calling user's own test results. Requires #user role.
   */
  'getMyResults' : ActorMethod<[], Array<TestResult>>,
  /**
   * / Get all published tests. Requires #user role.
   */
  'getPublishedTests' : ActorMethod<[], Array<CompleteTest>>,
  /**
   * / Get a test by ID. Non-admins can only access published tests.
   */
  'getTestById' : ActorMethod<[bigint], CompleteTest>,
  /**
   * / Get another user's profile. Caller must be the same user or an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Check if the caller has visited the admin.
   */
  'hasAdminBeenVisited' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Mark that the admin has been visited by the caller (admin only).
   */
  'markAdminVisited' : ActorMethod<[], undefined>,
  /**
   * / Register a new user profile. Requires #user role (must be authenticated).
   */
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Save the calling user's own profile. Requires #user role.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit a test result. Requires #user role.
   */
  'submitTestResult' : ActorMethod<[bigint, Array<Answer>, bigint], undefined>,
  /**
   * / Toggle publish/unpublish a test. Admin only.
   */
  'togglePublishTest' : ActorMethod<[bigint], undefined>,
  /**
   * / Update the calling user's profile. Requires #user role.
   */
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update an existing question. Admin only.
   */
  'updateQuestion' : ActorMethod<[bigint, ExternalBlob, string], undefined>,
  /**
   * / Update an existing test. Admin only.
   */
  'updateTest' : ActorMethod<
    [bigint, string, bigint, Array<bigint>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];