/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionId' : bigint, 'selectedOption' : string }
export type Class = { 'dropper' : null } |
  { 'eleventh' : null } |
  { 'twelfth' : null };
export interface CompleteTest {
  'id' : bigint,
  'isPublished' : boolean,
  'name' : string,
  'durationMinutes' : bigint,
  'marksPerCorrect' : bigint,
  'questions' : Array<Question>,
  'negativeMarks' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Question {
  'id' : bigint,
  'correctOption' : string,
  'image' : ExternalBlob,
}
export interface TestResult {
  'marks' : bigint,
  'userId' : Principal,
  'answers' : Array<Answer>,
  'submittedAt' : Time,
  'score' : bigint,
  'testId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'fullName' : string,
  'hasVisitedAdmin' : boolean,
  'contactNumber' : bigint,
  'userClass' : Class,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[ExternalBlob, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTest' : ActorMethod<
    [string, bigint, Array<bigint>, bigint, bigint],
    bigint
  >,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllResults' : ActorMethod<[], Array<TestResult>>,
  'getAllTests' : ActorMethod<[], Array<CompleteTest>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyResults' : ActorMethod<[], Array<TestResult>>,
  'getPublishedTests' : ActorMethod<[], Array<CompleteTest>>,
  'getTestById' : ActorMethod<[bigint], CompleteTest>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminBeenVisited' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAdminVisited' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTestResult' : ActorMethod<[bigint, Array<Answer>], undefined>,
  'togglePublishTest' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
  'updateQuestion' : ActorMethod<[bigint, ExternalBlob, string], undefined>,
  'updateTest' : ActorMethod<
    [bigint, string, bigint, Array<bigint>, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];